In [7]:
import numpy as np

def eig(A):# Поступает квадратная матрица, собсвтвенные векторы и числа которой нужно определить
    # Сначала находим собственые векторы и числа для матрицы 2x2. Для этого решаем характеристическое уравнение
    lmbd1 = (A[0,0]+A[1,1]+((A[0,0]+A[1,1])**2-4*(A[1,1]*A[0,0]-A[0,1]*A[1,0]))**(1/2))/2
    lmbd2 = (A[0,0]+A[1,1]-((A[0,0]+A[1,1])**2-4*(A[1,1]*A[0,0]-A[0,1]*A[1,0]))**(1/2))/2
    
    eigenvalues =  np.array([lmbd1, lmbd2])

    x01 = 1/((1+A[0,1]*A[1,0]/(A[0,0]-lmbd1)**2))**(1/2)
    x00 = -A[0,1]/(A[0,0]-lmbd1)*x01
    x11 = 1/((1+A[0,1]*A[1,0]/(A[0,0]-lmbd2)**2))**(1/2)
    x10 = -A[0,1]/(A[0,0]-lmbd2)*x11
    X = np.array([[x00,x01],[x10,x11]])

    xT01 = 1/((1+A[0,1]*A[1,0]/(A[0,0]-lmbd1)**2))**(1/2)
    xT00 = -A[1,0]/(A[0,0]-lmbd1)*xT01
    xT11 = 1/((1+A[0,1]*A[1,0]/(A[0,0]-lmbd2)**2))**(1/2)
    xT10 = -A[1,0]/(A[0,0]-lmbd2)*xT11
    XT = np.array([[xT00,xT01],[xT10,xT11]])
    print('dim = 2:',"\n")
    print('Собственные значения:','\n', *np.round(eigenvalues, 6), '\n')     
    print('Собственные векторы матрицы:','\n',np.round(X.transpose(), 6),'\n')
    print('Собственные векторы транспонированной матрицы:','\n',np.round(XT.transpose(), 6), '\n')
    print('Проверка перемножением:',"\n",np.round(X.transpose().dot(XT), 3)+0,'\n')
    # Находим собственные значения и собсвтенные векторы матрицы больших размерностей.
    for dim in range(3, len(A[0])+1):
        PT = A[0:dim-1, dim-1].dot(XT.transpose())
        P = A[dim-1, 0: dim-1].dot(X.transpose())
        
        M = P*PT
       
        poly = [0]*(dim+1)
        poly[0] = np.array([-1, A[dim-1,dim-1]])

        for r in range(1, dim):
            poly[r] = np.array([-1, eigenvalues[r-1]])

        from functools import reduce
        poly[dim] = reduce(lambda x, y: np.polymul(x, y), poly[1: dim])
        pd = reduce(lambda x, y: np.polymul(x, y), poly[0: dim])

        poly1 = [0]*(dim)
        poly1[0] = np.array(pd.copy())

        for r in range(1, dim):
            poly1[r] = np.polydiv(poly[dim], poly[r])[0]*(-M[r-1])

        p = reduce(lambda x, y: np.polyadd(x, y), poly1)
        eigenvalues_old = np.array(eigenvalues.copy())
        eigenvalues = np.array(np.roots(p).copy())
        
        X_old = np.array(X.copy())
        XT_old = np.array(XT.copy())
        X = np.array([[0.]*dim]*dim)
        XT= np.array([[0.]*dim]*dim)
        
        for i in range(dim):
            f = 1 + sum(M/(eigenvalues_old-eigenvalues[i])**2)
            if (f > 0):
                X[i, dim-1] = 1/(f)**(1/2)
                XT[i, dim-1] = 1/(f)**(1/2)
            else:
                X[i, dim-1] = 1/(-f)**(1/2)
                XT[i, dim-1] = -1/(-f)**(1/2)
            for j in range(dim-1):
                X[i, j] = -sum(PT*X_old[0:, j]/(eigenvalues_old-eigenvalues[i]))*X[i, dim-1]
                XT[i, j] = -sum(P*XT_old[0:, j]/(eigenvalues_old-eigenvalues[i]))*XT[i, dim-1]
        print('dim = ',dim,':',"\n", sep = '')
        print('Собственные значения:','\n', *np.round(eigenvalues, 6), '\n')     
        print('Собственные векторы матрицы:','\n',np.round(X.transpose(), 6),'\n')
        print('Собственные векторы транспонированной матрицы:','\n',np.round(XT.transpose(), 6), '\n')
        print('Проверка перемножением:','\n',np.round(X.transpose().dot(XT), 6)+0,'\n')
 
    


A = np.array([[1, 2, 3, 7], 
              [2, 2, 3, 9], 
              [3, 3, 3, 8],
              [7, 9, 8, 6]])

eig(A)

dim = 2: 

Собственные значения: 
 3.561553 -0.561553 

Собственные векторы матрицы: 
 [[ 0.615412 -0.788205]
 [ 0.788205  0.615412]] 

Собственные векторы транспонированной матрицы: 
 [[ 0.615412 -0.788205]
 [ 0.788205  0.615412]] 

Проверка перемножением: 
 [[1. 0.]
 [0. 1.]] 

dim = 3:

Собственные значения: 
 7.516538 -1.177617 -0.338922 

Собственные векторы матрицы: 
 [[ 0.482739 -0.765677  0.42509 ]
 [ 0.546963 -0.115485 -0.829153]
 [ 0.683955  0.632774  0.363048]] 

Собственные векторы транспонированной матрицы: 
 [[ 0.482739 -0.765677  0.42509 ]
 [ 0.546963 -0.115485 -0.829153]
 [ 0.683955  0.632774  0.363048]] 

Проверка перемножением: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

dim = 4:

Собственные значения: 
 20.648042 -7.379422 -1.08029 -0.18833 

Собственные векторы матрицы: 
 [[ 0.358836 -0.369244  0.759253 -0.398033]
 [ 0.442903 -0.513194 -0.075537  0.731275]
 [ 0.448387 -0.29662  -0.642454 -0.546094]
 [ 0.688493  0.715757  0.071281  0.092675]] 

Собственные векторы транс

In [8]:
np.linalg.det(A)
    

-31.0

In [9]:
np.linalg.eig(A)

(array([20.64804209, -7.37942155, -1.08029032, -0.18833022]),
 array([[ 0.35883572,  0.36924385, -0.75925343,  0.39803283],
        [ 0.44290286,  0.51319409,  0.07553696, -0.73127495],
        [ 0.44838743,  0.29661958,  0.64245419,  0.54609354],
        [ 0.68849306, -0.71575668, -0.07128127, -0.09267503]]))